<?php

class CountriesTableSeeder extends Seeder {

	public function run()
	{
		Country::truncate();

		Country::insert(array(
			array('id' => 'ad','country' => 'Andorra ','cleaned' => '1',),
			array('id' => 'ae','country' => 'United Arab Emirates ','cleaned' => '0',),
			array('id' => 'af','country' => 'Afghanistan ','cleaned' => '0',),
			array('id' => 'ag','country' => 'Antigua and Barbuda ','cleaned' => '0',),
			array('id' => 'ai','country' => 'Anguilla ','cleaned' => '0',),
			array('id' => 'al','country' => 'Albania ','cleaned' => '0',),
			array('id' => 'am','country' => 'Armenia ','cleaned' => '0',),
			array('id' => 'an','country' => 'Netherlands Antilles ','cleaned' => '0',),
			array('id' => 'ao','country' => 'Angola ','cleaned' => '0',),
			array('id' => 'aq','country' => 'Antarctica ','cleaned' => '0',),
			array('id' => 'ar','country' => 'Argentina ','cleaned' => '0',),
			array('id' => 'as','country' => 'American Samoa ','cleaned' => '0',),
			array('id' => 'at','country' => 'Austria ','cleaned' => '0',),
			array('id' => 'au','country' => 'Australia ','cleaned' => '0',),
			array('id' => 'aw','country' => 'Aruba ','cleaned' => '0',),
			array('id' => 'ax','country' => 'Åland Islands ','cleaned' => '0',),
			array('id' => 'az','country' => 'Azerbaijan ','cleaned' => '0',),
			array('id' => 'ba','country' => 'Bosnia and Herzegovina ','cleaned' => '0',),
			array('id' => 'bb','country' => 'Barbados ','cleaned' => '0',),
			array('id' => 'bd','country' => 'Bangladesh ','cleaned' => '0',),
			array('id' => 'be','country' => 'Belgium ','cleaned' => '0',),
			array('id' => 'bf','country' => 'Burkina Faso ','cleaned' => '0',),
			array('id' => 'bg','country' => 'Bulgaria ','cleaned' => '0',),
			array('id' => 'bh','country' => 'Bahrain ','cleaned' => '0',),
			array('id' => 'bi','country' => 'Burundi ','cleaned' => '0',),
			array('id' => 'bj','country' => 'Benin ','cleaned' => '0',),
			array('id' => 'bm','country' => 'Bermuda ','cleaned' => '0',),
			array('id' => 'bn','country' => 'Brunei Darussalam ','cleaned' => '0',),
			array('id' => 'bo','country' => 'Bolivia ','cleaned' => '0',),
			array('id' => 'br','country' => 'Brazil ','cleaned' => '0',),
			array('id' => 'bs','country' => 'Bahamas ','cleaned' => '0',),
			array('id' => 'bt','country' => 'Bhutan ','cleaned' => '0',),
			array('id' => 'bv','country' => 'Bouvet Island ','cleaned' => '0',),
			array('id' => 'bw','country' => 'Botswana ','cleaned' => '0',),
			array('id' => 'by','country' => 'Belarus ','cleaned' => '0',),
			array('id' => 'bz','country' => 'Belize ','cleaned' => '0',),
			array('id' => 'ca','country' => 'Canada ','cleaned' => '0',),
			array('id' => 'cc','country' => 'Cocos (Keeling) Islands ','cleaned' => '0',),
			array('id' => 'cd','country' => 'Democratic Republic of the Congo','cleaned' => '0',),
			array('id' => 'cf','country' => 'Central African Republic ','cleaned' => '0',),
			array('id' => 'cg','country' => 'Republic of the Congo ','cleaned' => '0',),
			array('id' => 'ch','country' => 'Switzerland ','cleaned' => '0',),
			array('id' => 'ci','country' => 'Côte d\'Ivoire ','cleaned' => '0',),
			array('id' => 'ck','country' => 'Cook Islands ','cleaned' => '0',),
			array('id' => 'cl','country' => 'Chile ','cleaned' => '0',),
			array('id' => 'cm','country' => 'Cameroon ','cleaned' => '0',),
			array('id' => 'cn','country' => 'China ','cleaned' => '0',),
			array('id' => 'co','country' => 'Colombia ','cleaned' => '0',),
			array('id' => 'cr','country' => 'Costa Rica ','cleaned' => '0',),
			array('id' => 'cu','country' => 'Cuba ','cleaned' => '0',),
			array('id' => 'cv','country' => 'Cape Verde ','cleaned' => '0',),
			array('id' => 'cx','country' => 'Christmas Island ','cleaned' => '0',),
			array('id' => 'cy','country' => 'Cyprus ','cleaned' => '0',),
			array('id' => 'cz','country' => 'Czech Republic ','cleaned' => '0',),
			array('id' => 'de','country' => 'Germany ','cleaned' => '0',),
			array('id' => 'dj','country' => 'Djibouti ','cleaned' => '0',),
			array('id' => 'dk','country' => 'Denmark ','cleaned' => '0',),
			array('id' => 'dm','country' => 'Dominica ','cleaned' => '0',),
			array('id' => 'do','country' => 'Dominican Republic ','cleaned' => '0',),
			array('id' => 'dz','country' => 'Algeria ','cleaned' => '0',),
			array('id' => 'ec','country' => 'Ecuador ','cleaned' => '0',),
			array('id' => 'ee','country' => 'Estonia ','cleaned' => '0',),
			array('id' => 'eg','country' => 'Egypt ','cleaned' => '0',),
			array('id' => 'eh','country' => 'Western Sahara ','cleaned' => '0',),
			array('id' => 'er','country' => 'Eritrea ','cleaned' => '0',),
			array('id' => 'es','country' => 'Spain ','cleaned' => '0',),
			array('id' => 'et','country' => 'Ethiopia ','cleaned' => '0',),
			array('id' => 'fi','country' => 'Finland ','cleaned' => '0',),
			array('id' => 'fj','country' => 'Fiji ','cleaned' => '0',),
			array('id' => 'fk','country' => 'Falkland Islands (Malvinas) ','cleaned' => '0',),
			array('id' => 'fm','country' => 'Federated States of Micronesia','cleaned' => '0',),
			array('id' => 'fo','country' => 'Faroe Islands ','cleaned' => '0',),
			array('id' => 'fr','country' => 'France ','cleaned' => '0',),
			array('id' => 'ga','country' => 'Gabon ','cleaned' => '0',),
			array('id' => 'gb','country' => 'United Kingdom ','cleaned' => '0',),
			array('id' => 'gd','country' => 'Grenada ','cleaned' => '0',),
			array('id' => 'ge','country' => 'Georgia ','cleaned' => '0',),
			array('id' => 'gf','country' => 'French Guiana ','cleaned' => '0',),
			array('id' => 'gg','country' => 'Guernsey ','cleaned' => '0',),
			array('id' => 'gh','country' => 'Ghana ','cleaned' => '0',),
			array('id' => 'gi','country' => 'Gibraltar ','cleaned' => '0',),
			array('id' => 'gl','country' => 'Greenland ','cleaned' => '0',),
			array('id' => 'gm','country' => 'Gambia ','cleaned' => '0',),
			array('id' => 'gn','country' => 'Guinea ','cleaned' => '0',),
			array('id' => 'gp','country' => 'Guadeloupe ','cleaned' => '0',),
			array('id' => 'gq','country' => 'Equatorial Guinea ','cleaned' => '0',),
			array('id' => 'gr','country' => 'Greece ','cleaned' => '0',),
			array('id' => 'gs','country' => 'South Georgia and the South Sandwich Islands ','cleaned' => '0',),
			array('id' => 'gt','country' => 'Guatemala ','cleaned' => '0',),
			array('id' => 'gu','country' => 'Guam ','cleaned' => '0',),
			array('id' => 'gw','country' => 'Guinea-Bissau ','cleaned' => '0',),
			array('id' => 'gy','country' => 'Guyana ','cleaned' => '0',),
			array('id' => 'hk','country' => 'Hong Kong ','cleaned' => '0',),
			array('id' => 'hm','country' => 'Heard Island and McDonald Islands ','cleaned' => '0',),
			array('id' => 'hn','country' => 'Honduras ','cleaned' => '0',),
			array('id' => 'hr','country' => 'Croatia ','cleaned' => '0',),
			array('id' => 'ht','country' => 'Haiti ','cleaned' => '0',),
			array('id' => 'hu','country' => 'Hungary ','cleaned' => '0',),
			array('id' => 'id','country' => 'Indonesia ','cleaned' => '0',),
			array('id' => 'ie','country' => 'Ireland ','cleaned' => '0',),
			array('id' => 'il','country' => 'Israel ','cleaned' => '0',),
			array('id' => 'im','country' => 'Isle of Man ','cleaned' => '0',),
			array('id' => 'in','country' => 'India ','cleaned' => '0',),
			array('id' => 'io','country' => 'British Indian Ocean Territory ','cleaned' => '0',),
			array('id' => 'iq','country' => 'Iraq ','cleaned' => '0',),
			array('id' => 'ir','country' => 'Islamic Republic of Iran','cleaned' => '0',),
			array('id' => 'is','country' => 'Iceland ','cleaned' => '0',),
			array('id' => 'it','country' => 'Italy ','cleaned' => '0',),
			array('id' => 'je','country' => 'Jersey ','cleaned' => '0',),
			array('id' => 'jm','country' => 'Jamaica ','cleaned' => '0',),
			array('id' => 'jo','country' => 'Jordan ','cleaned' => '0',),
			array('id' => 'jp','country' => 'Japan ','cleaned' => '0',),
			array('id' => 'ke','country' => 'Kenya ','cleaned' => '0',),
			array('id' => 'kg','country' => 'Kyrgyzstan ','cleaned' => '0',),
			array('id' => 'kh','country' => 'Cambodia ','cleaned' => '0',),
			array('id' => 'ki','country' => 'Kiribati ','cleaned' => '0',),
			array('id' => 'km','country' => 'Comoros ','cleaned' => '0',),
			array('id' => 'kn','country' => 'Saint Kitts and Nevis ','cleaned' => '0',),
			array('id' => 'kp','country' => 'Democratic People\'s Republic of Korea','cleaned' => '0',),
			array('id' => 'kr','country' => 'Republic of Korea','cleaned' => '0',),
			array('id' => 'kv','country' => 'Kosovo','cleaned' => '0',),
			array('id' => 'kw','country' => 'Kuwait ','cleaned' => '0',),
			array('id' => 'ky','country' => 'Cayman Islands ','cleaned' => '0',),
			array('id' => 'kz','country' => 'Kazakhstan ','cleaned' => '0',),
			array('id' => 'la','country' => 'Lao People\'s Democratic Republic ','cleaned' => '0',),
			array('id' => 'lb','country' => 'Lebanon ','cleaned' => '0',),
			array('id' => 'lc','country' => 'Saint Lucia ','cleaned' => '0',),
			array('id' => 'li','country' => 'Liechtenstein ','cleaned' => '0',),
			array('id' => 'lk','country' => 'Sri Lanka ','cleaned' => '0',),
			array('id' => 'lr','country' => 'Liberia ','cleaned' => '0',),
			array('id' => 'ls','country' => 'Lesotho ','cleaned' => '0',),
			array('id' => 'lt','country' => 'Lithuania ','cleaned' => '0',),
			array('id' => 'lu','country' => 'Luxembourg ','cleaned' => '0',),
			array('id' => 'lv','country' => 'Latvia ','cleaned' => '0',),
			array('id' => 'ly','country' => 'Libyan Arab Jamahiriya ','cleaned' => '0',),
			array('id' => 'ma','country' => 'Morocco ','cleaned' => '0',),
			array('id' => 'mc','country' => 'Monaco ','cleaned' => '0',),
			array('id' => 'md','country' => 'Republic of Moldova','cleaned' => '0',),
			array('id' => 'me','country' => 'Montenegro ','cleaned' => '0',),
			array('id' => 'mg','country' => 'Madagascar ','cleaned' => '0',),
			array('id' => 'mh','country' => 'Marshall Islands ','cleaned' => '0',),
			array('id' => 'mk','country' => 'Macedonia','cleaned' => '0',),
			array('id' => 'ml','country' => 'Mali ','cleaned' => '0',),
			array('id' => 'mm','country' => 'Myanmar ','cleaned' => '0',),
			array('id' => 'mn','country' => 'Mongolia ','cleaned' => '0',),
			array('id' => 'mo','country' => 'Macao ','cleaned' => '0',),
			array('id' => 'mp','country' => 'Northern Mariana Islands ','cleaned' => '0',),
			array('id' => 'mq','country' => 'Martinique ','cleaned' => '0',),
			array('id' => 'mr','country' => 'Mauritania ','cleaned' => '0',),
			array('id' => 'ms','country' => 'Montserrat ','cleaned' => '0',),
			array('id' => 'mt','country' => 'Malta ','cleaned' => '0',),
			array('id' => 'mu','country' => 'Mauritius ','cleaned' => '0',),
			array('id' => 'mv','country' => 'Maldives ','cleaned' => '0',),
			array('id' => 'mw','country' => 'Malawi ','cleaned' => '0',),
			array('id' => 'mx','country' => 'Mexico ','cleaned' => '0',),
			array('id' => 'my','country' => 'Malaysia ','cleaned' => '0',),
			array('id' => 'mz','country' => 'Mozambique ','cleaned' => '0',),
			array('id' => 'na','country' => 'Namibia ','cleaned' => '0',),
			array('id' => 'nc','country' => 'New Caledonia ','cleaned' => '0',),
			array('id' => 'ne','country' => 'Niger ','cleaned' => '0',),
			array('id' => 'nf','country' => 'Norfolk Island ','cleaned' => '0',),
			array('id' => 'ng','country' => 'Nigeria ','cleaned' => '0',),
			array('id' => 'ni','country' => 'Nicaragua ','cleaned' => '0',),
			array('id' => 'nl','country' => 'Netherlands ','cleaned' => '0',),
			array('id' => 'no','country' => 'Norway ','cleaned' => '0',),
			array('id' => 'np','country' => 'Nepal ','cleaned' => '0',),
			array('id' => 'nr','country' => 'Nauru ','cleaned' => '0',),
			array('id' => 'nu','country' => 'Niue ','cleaned' => '0',),
			array('id' => 'nz','country' => 'New Zealand ','cleaned' => '0',),
			array('id' => 'om','country' => 'Oman ','cleaned' => '0',),
			array('id' => 'pa','country' => 'Panama ','cleaned' => '0',),
			array('id' => 'pe','country' => 'Peru ','cleaned' => '0',),
			array('id' => 'pf','country' => 'French Polynesia ','cleaned' => '0',),
			array('id' => 'pg','country' => 'Papua New Guinea ','cleaned' => '0',),
			array('id' => 'ph','country' => 'Philippines ','cleaned' => '0',),
			array('id' => 'pk','country' => 'Pakistan ','cleaned' => '0',),
			array('id' => 'pl','country' => 'Poland ','cleaned' => '0',),
			array('id' => 'pm','country' => 'Saint Pierre and Miquelon ','cleaned' => '0',),
			array('id' => 'pn','country' => 'Pitcairn ','cleaned' => '0',),
			array('id' => 'pr','country' => 'Puerto Rico ','cleaned' => '0',),
			array('id' => 'ps','country' => 'Palestinian Territory','cleaned' => '0',),
			array('id' => 'pt','country' => 'Portugal ','cleaned' => '0',),
			array('id' => 'pw','country' => 'Palau ','cleaned' => '0',),
			array('id' => 'py','country' => 'Paraguay ','cleaned' => '0',),
			array('id' => 'qa','country' => 'Qatar ','cleaned' => '0',),
			array('id' => 're','country' => 'Réunion ','cleaned' => '0',),
			array('id' => 'ro','country' => 'Romania ','cleaned' => '0',),
			array('id' => 'rs','country' => 'Serbia ','cleaned' => '0',),
			array('id' => 'ru','country' => 'Russian Federation ','cleaned' => '0',),
			array('id' => 'rw','country' => 'Rwanda ','cleaned' => '0',),
			array('id' => 'sa','country' => 'Saudi Arabia ','cleaned' => '0',),
			array('id' => 'sb','country' => 'Solomon Islands ','cleaned' => '0',),
			array('id' => 'sc','country' => 'Seychelles ','cleaned' => '0',),
			array('id' => 'sd','country' => 'Sudan ','cleaned' => '0',),
			array('id' => 'se','country' => 'Sweden ','cleaned' => '0',),
			array('id' => 'sg','country' => 'Singapore ','cleaned' => '0',),
			array('id' => 'sh','country' => 'Saint Helena ','cleaned' => '0',),
			array('id' => 'si','country' => 'Slovenia ','cleaned' => '0',),
			array('id' => 'sj','country' => 'Svalbard and Jan Mayen ','cleaned' => '0',),
			array('id' => 'sk','country' => 'Slovakia ','cleaned' => '0',),
			array('id' => 'sl','country' => 'Sierra Leone ','cleaned' => '0',),
			array('id' => 'sm','country' => 'San Marino ','cleaned' => '0',),
			array('id' => 'sn','country' => 'Senegal ','cleaned' => '0',),
			array('id' => 'so','country' => 'Somalia ','cleaned' => '0',),
			array('id' => 'sr','country' => 'Suriname ','cleaned' => '0',),
			array('id' => 'st','country' => 'Sao Tome and Principe ','cleaned' => '0',),
			array('id' => 'sv','country' => 'El Salvador ','cleaned' => '0',),
			array('id' => 'sy','country' => 'Syrian Arab Republic ','cleaned' => '0',),
			array('id' => 'sz','country' => 'Swaziland ','cleaned' => '0',),
			array('id' => 'tc','country' => 'Turks and Caicos Islands ','cleaned' => '0',),
			array('id' => 'td','country' => 'Chad ','cleaned' => '0',),
			array('id' => 'tf','country' => 'French Southern Territories ','cleaned' => '0',),
			array('id' => 'tg','country' => 'Togo ','cleaned' => '0',),
			array('id' => 'th','country' => 'Thailand ','cleaned' => '0',),
			array('id' => 'tj','country' => 'Tajikistan ','cleaned' => '0',),
			array('id' => 'tk','country' => 'Tokelau ','cleaned' => '0',),
			array('id' => 'tl','country' => 'Timor-Leste ','cleaned' => '0',),
			array('id' => 'tm','country' => 'Turkmenistan ','cleaned' => '0',),
			array('id' => 'tn','country' => 'Tunisia ','cleaned' => '0',),
			array('id' => 'to','country' => 'Tonga ','cleaned' => '0',),
			array('id' => 'tr','country' => 'Turkey ','cleaned' => '0',),
			array('id' => 'tt','country' => 'Trinidad and Tobago ','cleaned' => '0',),
			array('id' => 'tv','country' => 'Tuvalu ','cleaned' => '0',),
			array('id' => 'tw','country' => 'Taiwan','cleaned' => '0',),
			array('id' => 'tz','country' => 'Tanzania','cleaned' => '0',),
			array('id' => 'ua','country' => 'Ukraine ','cleaned' => '0',),
			array('id' => 'ug','country' => 'Uganda ','cleaned' => '0',),
			array('id' => 'um','country' => 'United States Minor Outlying Islands ','cleaned' => '0',),
			array('id' => 'un','country' => 'United Nations','cleaned' => '0',),
			array('id' => 'us','country' => 'United States ','cleaned' => '0',),
			array('id' => 'uy','country' => 'Uruguay ','cleaned' => '0',),
			array('id' => 'uz','country' => 'Uzbekistan ','cleaned' => '0',),
			array('id' => 'va','country' => 'Holy See (Vatican City State) ','cleaned' => '0',),
			array('id' => 'vc','country' => 'Saint Vincent and the Grenadines ','cleaned' => '0',),
			array('id' => 've','country' => 'Venezuela ','cleaned' => '0',),
			array('id' => 'vg','country' => 'British Virgin Islands','cleaned' => '0',),
			array('id' => 'vi','country' => 'U.S. Virgin Islands','cleaned' => '0',),
			array('id' => 'vn','country' => 'Vietnam','cleaned' => '0',),
			array('id' => 'vu','country' => 'Vanuatu ','cleaned' => '0',),
			array('id' => 'wf','country' => 'Wallis and Futuna ','cleaned' => '0',),
			array('id' => 'ws','country' => 'Samoa ','cleaned' => '0',),
			array('id' => 'ye','country' => 'Yemen ','cleaned' => '0',),
			array('id' => 'yt','country' => 'Mayotte ','cleaned' => '0',),
			array('id' => 'za','country' => 'South Africa ','cleaned' => '0',),
			array('id' => 'zm','country' => 'Zambia ','cleaned' => '0',),
			array('id' => 'zw','country' => 'Zimbabwe ','cleaned' => '0',),
		));
	}

}